services:
  api-gateway:
    image: kong:3.9.1
    container_name: api-gateway
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    volumes:
      - ./configs/kong/kong.yaml:/kong/kong.yaml:ro
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    depends_on:
      users-service:
        condition: service_healthy

  users-db:
    image: postgres:15
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socmed_users
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d socmed_users -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - users-db:/var/lib/postgresql/data
volumes:
  users-db:
