FROM golang:1.25.3-alpine

WORKDIR /app
ARG SERVICE=follow

RUN go install github.com/air-verse/air@latest

# Copy all modules used in the workspace
COPY common/go.mod common/go.sum ./common/
COPY ${SERVICE}/go.mod ${SERVICE}/go.sum ./${SERVICE}/

# Copy workspace definition
RUN go work init && go work use common ${SERVICE}

# Pre-download all dependencies
RUN go work sync && go mod download

COPY common/ ./common
COPY ${SERVICE}/ ./${SERVICE}

WORKDIR /app/${SERVICE}

CMD ["air"]
